use sakila; -- by Amir Alsayed :__:

--  User-Defined Functions

-- 1. Create a function that takes actor_id and returns the concatenated first and last name of this actor. 

drop function if exists get_full_name ;

delimiter ##
create function get_full_name(actor_id int)
returns varchar(255)
reads sql data
begin
	declare full_name varchar(255);
    select concat(first_name, " ", last_name) into full_name
    from actor a
    where a.actor_id = actor_id;
    return full_name;
end ##
delimiter ;

select get_full_name(actor_id)
from actor;

-- 2. Create a function that takes customer_id and returns the total count of rentals made by this customer. 

drop function if exists count_renals;

delimiter ##
create function count_renals(customer_id int)
returns int
reads sql data
begin
	declare output int;
    select count(*) into output
    from rental r
    where r.customer_id = customer_id;
	
	return output;
end ##
delimiter ;

select distinct customer_id, count_renals(customer_id)
from rental;

-- 3. Create a function that takes a DECIMAL value and returns it as a formatted string with a dollar sign (e.g., $19.99).

drop function if exists format_currency;

delimiter ##
create function format_currency(amount decimal(10,2))
returns varchar(20)
deterministic
begin
    return concat('$', format(amount, 2));
end ##
delimiter ;

select format_currency(19.99) as test_price, format_currency(5) as test_integer;

-- 4. Create a stored procedure that takes customer_id and returns a result set containing the full name, email, full address, and city of that customer.

drop procedure if exists get_customer_contact;

delimiter ##
create procedure get_customer_contact(in p_customer_id int)
begin
    select 
        concat(first_name, ' ', last_name) as full_name,
        email,
        a.address as full_address,
        c.city
    from customer cu
    join address a on cu.address_id = a.address_id
    join city c on a.city_id = c.city_id
    where cu.customer_id = p_customer_id;
end ##
delimiter ;

call get_customer_contact(5);


-- 5. Create a stored procedure that takes a start_date and end_date and returns the total revenue generated by each store during that period.

drop procedure if exists get_store_revenue;

delimiter ##
create procedure get_store_revenue(in start_date date, in end_date date)
begin
    select 
        s.store_id,
        sum(p.amount) as total_revenue
    from payment p
    join staff st on p.staff_id = st.staff_id
    join store s on st.store_id = s.store_id
    where date(p.payment_date) between start_date and end_date -- yyyy-mm-dd
    group by s.store_id;
end ##
delimiter ;

call get_store_revenue('2005-01-01', '2005-12-31');


-- 6. Create a stored procedure that takes a partial string (e.g., 'dark') and returns all films whose titles contain that string, along with their ratings.

drop procedure if exists search_films;

delimiter ##
create procedure search_films(in genra varchar(255))
begin
    select title, rating
    from film
    where title like concat('%', genra, '%');
end ##
delimiter ;

call search_films('dark');


-- 7. Create a stored procedure that takes customer_id and returns the name of the category (e.g., 'Action') that the customer rents most often.

drop procedure if exists get_favorite_category;

delimiter ##
create procedure get_favorite_category(in p_customer_id int)
begin
    select c.name as category_name
    from rental r
    join inventory i on r.inventory_id = i.inventory_id
    join film_category fc on i.film_id = fc.film_id
    join category c on fc.category_id = c.category_id
    where r.customer_id = p_customer_id
    group by c.name
    order by count(*) desc
    limit 1;
end ##
delimiter ;

call get_favorite_category(2);


-- 8. Create a BEFORE UPDATE trigger on address table to set last_update = NOW() whenever a row is changed.

drop trigger if exists trg_address_update;

delimiter ##
create trigger trg_address_update
before update on address
for each row
begin
    set NEW.last_update = now();
end ##
delimiter ;

-- TEST 8
update address
set address2 = 'Test Update '
where address_id = 1;
select address_id, address2, last_update
from address 
where address_id = 1;


-- 9. Create a trigger to prevent an UPDATE to the staff table if the username is changed to 'admin'.

drop trigger if exists trg_prevent_admin_username;

delimiter ##
create trigger trg_prevent_admin_username
before update on staff
for each row
begin
    if NEW.username = 'admin' then
        signal sqlstate '45000'
        set message_text = 'Error: The username "admin" is restricted and cannot be used.';
    end if;
end ##
delimiter ;

update staff 
set username = 'admin' 
where staff_id = 1;


-- 10. Create a BEFORE INSERT trigger on the customer table to ensure that any email address entered contains both an @ and a . symbol.

drop trigger if exists trg_validate_email;

delimiter ##
create trigger trg_validate_email
before insert on customer
for each row
begin
    if NEW.email not like '%@%' or NEW.email not like '%.%' then
        signal sqlstate '45000'
        set message_text = 'Error: Invalid email format. Must contain @ and .';
    end if;
end ##
delimiter ;

insert into customer (store_id, first_name, last_name, email, address_id, active) 
values (1, 'Test', 'User', 'botato', 1, 1);


-- 11. Create a table film_price_history. Create an AFTER UPDATE trigger on the film table that records the old price, new price, and change date whenever the rental_rate is modified.

drop table if exists film_price_history;
create table film_price_history (
    history_id int auto_increment primary key,
    old_price decimal(4,2),
    new_price decimal(4,2),
    title varchar(100),
    change_date datetime
);

drop trigger if exists trg_film_rental_rate_history;

delimiter ##
create trigger trg_film_rental_rate_history
after update on film
for each row
begin
    if OLD.rental_rate <> NEW.rental_rate then
        insert into film_price_history (title, old_price, new_price, change_date)
        values (OLD.title, OLD.rental_rate, NEW.rental_rate, now());
    end if;
end ##
delimiter ;

-- TEST 11
update  film 
set rental_rate = 14
where film_id = 1;
select * 
from film_price_history;